In [2]:
#3-2 一次元配列の作成

import numpy as np
narray = np.array([1, 2, 3])
narray


array([1, 2, 3])

In [2]:
# 一次元配列のサイズの確認
narray.size

3

In [3]:
# 一次元配列の型の確認
type(narray)

numpy.ndarray

In [4]:
nones = np.ones(10)
nones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
type(nones)

numpy.ndarray

In [9]:
multi_array = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8, 9]])
multi_array

<ipython-input-9-604c1fd5ffd8>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  multi_array = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8, 9]])


array([list([0, 1, 2]), list([3, 4, 5]), list([6, 7, 8, 9])], dtype=object)

In [13]:
# 乱数の作成
np.random.rand(3, 3)

array([[0.71533315, 0.28864382, 0.38922903],
       [0.10275727, 0.0110941 , 0.31046605],
       [0.37630033, 0.51346873, 0.28164574]])

In [15]:
np.random.randint(1, 10)


9

In [64]:
# 整数の乱数で一次元配列の作成
np.random.randint(1, 10, (5,))

array([1, 6, 7, 7, 8])

In [16]:
np.random.randint(1, 10, (5,5))

array([[6, 5, 3, 9, 5],
       [9, 4, 9, 7, 2],
       [3, 7, 7, 8, 1],
       [5, 5, 6, 1, 1],
       [5, 1, 3, 3, 5]])

In [17]:
random_multi_array = np.random.randint(1, 10, (5,5))
random_multi_array

array([[6, 8, 6, 7, 3],
       [8, 9, 9, 1, 3],
       [9, 9, 7, 5, 8],
       [9, 7, 6, 6, 3],
       [5, 5, 9, 3, 7]])

In [18]:
random_multi_array.max()

9

In [68]:
random_multi_array.min()

1

In [19]:
# スライシング
random_array = np.random.randint(1, 10, (10,))
random_array

array([4, 5, 2, 1, 2, 7, 8, 9, 3, 5])

In [22]:
# 次に、先頭から3つの要素を取得しましょう。インデックスで表すならば、インデックスが0から2までの要素を取得します。
# これは、コロン（:）を使って次のように書きます。
random_array[0:3]

array([4, 5, 2])

In [23]:
# 3.5 配列の結合
# 「最終的な出力を結合して予測の答えとしたい」というようなこと
# 配列aと配列bを作り、結合するにはnumpy.concatenateメソッドを以下のように使う
a  = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [25]:
# 多次元配列として3x2の形にしてみましょう。行で結合するには、axis=0を次のように引数として渡します
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])

np.concatenate((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# NumPyでの足し算を行うためにnumpy.onesメソッドを使って、サイズが3の一次元配列を作ります。

three = np.ones(3)
three

array([1., 1., 1.])

In [5]:
# NumPyのブロードキャスト機能を使って3を足してみましょう。このブロードキャストは、以下の画像のようになります。
three + 3

array([4., 4., 4.])

In [3]:
# 多次元配列の足し算
# numpy.arangeメソッドで[0, 1, 2, 3, 4, 5]という一次元配列を作成し、
# numpy.reshapeというメソッドで配列の形状を2x3にします。

six_reshape = np.arange(6).reshape(2, 3)
six_reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [2]:
import numpy as np

In [4]:
# ブロードキャスト機能を使って1を足す
six_reshape + 1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# ブロードキャスト機能を使わず書く
si_reshape + np.array([[1, 0, 2],[1, 0, 2]])

In [2]:
# 引き算
import numpy as np

five_full = np.full(5, 5)
five_full




array([5, 5, 5, 5, 5])

In [3]:
# 一次元配列から値を引きます。まずは、ブロードキャスト機能を使って以下のような引き算をしてみましょう。
five_full -2


array([3, 3, 3, 3, 3])

In [4]:
# すべての要素から2を引いた一次元配列が返されました。
# 次にブロードキャスト機能を使わず、以下のようにも書けます。
five_full - np.array([1, 2, 3, 4, 5])

array([4, 3, 2, 1, 0])

In [6]:
# 掛け算
import numpy as np


In [19]:
ten = np.arange(6).reshape(2, 3)
ten

array([[0, 1, 2],
       [3, 4, 5]])

ten = [0, 1, 2, 3, 4, 5, 6, 7 ,8, 9]
ten = * 3
= [0, 1, 2, 3, 4, 5, 6, 7 ,8, 9] × [3, 3, 3, 3, 3, 3, 3, 3, 3]がブロードキャスト機能


In [20]:
# 記述コード
ten * 3

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [30]:
# ブロードキャスト機能を使わずにかける
ten * np.array([[1, 2, 2], [2, 3, 3]])

array([[ 0,  2,  4],
       [ 6, 12, 15]])

In [35]:
# 割り算

div_six = np.arange(6).reshape(2, 3)
div_six

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
# ブロードキャストを使う
div_six / 2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5]])

In [40]:
# ブロードキャストを使わない
div_six / np.array([[2, 2, 2],[2, 2, 2]])

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5]])

3.7 行列演算



In [41]:
# numpy.dotを使って積を出す
A = np.array([[4, 7, 2],[1, 2, 1]])
B = np.array([[2, 3, 3],[4, 5, 2],[9, 2, 1]])
np.dot(A, B)

array([[54, 51, 28],
       [19, 15,  8]])

NumPyを使って逆行列を求める


In [43]:
# NymPyを使って、ある行列を単位行列に変換する「逆行列」を求めるには
# numpy.linalg.invメソッドを使います。
#  逆行列を求めるメゾットをインポート
from numpy.linalg import inv
A = np.array([[1, 1, 0],[0, 1, 0],[0, 0, 1]])
ainv = inv(A)
ainv

array([[ 1., -1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [45]:
# この逆行列ainvと行列Aを掛けて本当に単位行列になるか確かめる
np.dot(A, ainv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3.8 合計・標準偏差などの計算
一次元配列、多次元配列の合計、中央値、標準偏差などの統計量を求めます。これらの処理は統計や機械学習では頻繁に使うため、ぜひ覚えておきましょう。

In [47]:
# 合計値を計算する
# まず配列の合計を求めるnumpy.sumメソッド
a = np.array([1, 2, 3])
np.sum(a)

6

次元配列の合計値を求める方法です。これには3種類あります。

In [48]:
# 全要素を足す方法
a = ([14, 8, 11, 10], [7, 9, 10, 11],[10, 15, 5, 10])
np.sum(a)


120

上記は
a = ([14, 8, 11, 10], [7, 9, 10, 11],[10, 15, 5, 10])
np.sum(a)
＝１４＋８＋１１＋１０＋９＋１０＋１１＋１０＋１５＋５＋１０＝１２０

In [49]:
# 　配列aを列で足す方法です。これは、axis=0を引数として与えます。
np.sum(a, axis=0)


array([31, 32, 26, 31])

In [50]:
np.sum(a, axis=1)

array([43, 37, 40])

中央値を計算する
一次元配列aの中央値を求める方法を紹介します。中央値とは、データを小さい数から大きい数へ並べたときの中央にある数字のことです。

偶数の場合は2つの数字の平均となります。平均とは違ってデータのノイズ（居所的に大きい値や小さい値の外れ値）に左右されないところがメリットです。

では、実際に配列aの中央値を求めましょう。

In [54]:
# 配列aの中央値を求める

a = np.array([1, 2, 3, 4])
np.median(a)
# 結果として中央値は2と3の平均である2.5であることが確認できました。

2.5

標準偏差を計算する
標準偏差とはデータのばらつきを表現する尺度です。平均からどれくらいデータがばらついているかを表します。

たとえば例えば、平均が10で標準偏差が5だとしたら、平均10±5のあたりに大体の値が存在するということを意味します。

では、実際に配列aの標準偏差を求めましょう。

In [53]:
a = np.array([1, 2, 3, 4, 5])
np.std(a)
# この結果は、平均点から約±1.412のところに大体の値が収まることを意味しています。

1.4142135623730951

3.9 NumPyを使った画像処理

In [63]:
from PIL import Image
import numpy as np

# 画像を読み込む
im = Image.open("camera.jpg")
im = im.resize((im.width //2, im.height //2)) # 元の画像はデカいので縮小
im
#

FileNotFoundError: [Errno 2] No such file or directory: 'camera.jpg'

課題　numpyで配列の操作や演算をしよう

In [2]:
#numpyのインポートを実行
import numpy as np

# AとBの行列を格納する多次元配列のコードを書く
A = ([0, 1],[2, 3],[4,5])
B = ([0, 1, 2, 3],[4, 5, 6, 7])
np.dot(A, B)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [14]:
# 最大値を求めるコードを書く
a = ([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])
np.max(a)

47